on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t drjseifu/enku-backend .
      - name: Publish Docker image
        run: docker push drjseifu/enku-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Enku AWS Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.ENKU_AWS_HOST }}
          username: ${{ secrets.ENKU_AWS_USER }}
          password: ${{ secrets.ENKU_AWS_PASSWORD }} # Add this line for password authentication
          port: 22
          script: |
            sudo docker rmi -f drjseifu/enku-backend:latest
            sudo docker-compose -f enku-docker-compose.yml up -d
        env:
          SSH_VERBOSE: "-vvv"
