name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t drjseifu/enku-backend .
      
      - name: Publish Docker image
        run: docker push drjseifu/enku-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH and run commands
        run: |
          echo "${{ secrets.ENKU_AWS_PASSWORD }}" | sshpass ssh -o StrictHostKeyChecking=no "${{ secrets.ENKU_AWS_USER }}@${{ secrets.ENKU_AWS_HOST }}" << 'EOF'
            # Commands to run on the server
            echo "${{ secrets.ENKU_AWS_PASSWORD }}" | sudo -S docker-compose pull
            echo "${{ secrets.ENKU_AWS_PASSWORD }}" | sudo -S docker-compose up -d
          EOF
