name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      # - name: Run seed
      #   run: npm run seed
        
      - name: Deploy to cPanel
        env:
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_SSH_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          # JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "${{ secrets.CPANEL_SSH_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
            cd /home/${{ secrets.CPANEL_USER }}/enkuapi.com
            git pull origin main
            npm install
            pm2 restart api || pm2 start src/app.js --name "enkuapi.com"
          EOF
